In [5]:
import numpy as np

# 学习网站 runoob

In [2]:
np.__version__

'1.19.4'

## python list

In [4]:
li = list(range(0,9))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
li[5] = 'll'

In [6]:
li

[0, 1, 2, 3, 4, 'll', 6, 7, 8]

## list 效率不高，所以可以使用array

## python array    初始化必须同一种数据类型
array 处理数据效率比list高，缺点是如果列表是多维的，矩阵操作不方便

In [7]:
import array
arr = array.array('i', list(range(10)))
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[6] = 'ddd'

TypeError: an integer is required (got type str)

In [9]:
arr[5] = 777

In [10]:
arr

array('i', [0, 1, 2, 3, 4, 777, 6, 7, 8, 9])

## numpy.ndarray

In [11]:
nparr = np.array(list(range(10)))
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(nparr)

numpy.ndarray

In [14]:
nparr.dtype

dtype('int32')

In [15]:
nparr[3] = 33
nparr

array([ 0,  1,  2, 33,  4,  5,  6,  7,  8,  9])

In [16]:
nparr[5]=66.55
nparr

array([ 0,  1,  2, 33,  4, 66,  6,  7,  8,  9])

In [18]:
 nparr2 = np.array([1,2,3.55])

In [22]:
nparr2.dtype

dtype('float64')

In [23]:
nparr3 = np.array([1,2,3], dtype=float)

In [25]:
nparr3

array([1., 2., 3.])

## 1.方便处理多维数组或者矩阵之间的运算
## 2.在处理多维度数组或者矩阵，运算效率高

In [4]:
def python_test(n):
    a = [i**2 for i in range(n)]
    b = [i**3 for i in range(n)]    
    c = []
    for i in range(n):
        c.append(a[i] + b[i])
    return c

python_test(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [6]:
def numpy_test(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

numpy_test(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810], dtype=int32)

In [9]:
%time res = python_test(10)

Wall time: 0 ns


In [31]:
%time res = numpy_test(1000000)

Wall time: 55 ms


## 矩阵和随机数的生成

In [32]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(2,20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [35]:
np.arange(2,20, 0.3)

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,  8.3,
        8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4, 10.7, 11. , 11.3, 11.6,
       11.9, 12.2, 12.5, 12.8, 13.1, 13.4, 13.7, 14. , 14.3, 14.6, 14.9,
       15.2, 15.5, 15.8, 16.1, 16.4, 16.7, 17. , 17.3, 17.6, 17.9, 18.2,
       18.5, 18.8, 19.1, 19.4, 19.7])

In [37]:
# np.zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# shape
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
# np.ones
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
np.full(10, 99)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [45]:
np.full((3,5), 'a')

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [46]:
# 等差数列
np.linspace(0,20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## 生成随机数

In [48]:
np.random.randint(0, 10)

5

In [51]:
np.random.randint(0, 10, size = 5)

array([4, 3, 2, 6, 0])

In [52]:
np.random.randint(0, 10, size = (2, 5))

array([[6, 8, 7, 2, 8],
       [5, 6, 8, 5, 7]])

In [53]:
np.random.randint(0, 10, size = (2, 5, 2))

array([[[5, 2],
        [8, 1],
        [6, 9],
        [5, 4],
        [2, 1]],

       [[5, 2],
        [0, 1],
        [3, 9],
        [1, 7],
        [2, 4]]])

In [56]:
np.random.seed(99)
np.random.randint(1, 10, 5)

array([2, 4, 9, 9, 3])

In [59]:
np.random.random() # 得到0-1的浮点数

0.9773480616332776

In [62]:
np.random.random((2,5))

array([[0.27198084, 0.39837991, 0.17442025, 0.50841827, 0.29519245],
       [0.27854534, 0.9705429 , 0.16296097, 0.78505862, 0.69391401]])

In [63]:
np.random.random((2,5,5))

array([[[0.61405019, 0.59362015, 0.07559798, 0.84728503, 0.92704652],
        [0.75859756, 0.90454277, 0.71629914, 0.70561847, 0.05063383],
        [0.14644117, 0.03266133, 0.11783106, 0.57269606, 0.11709176],
        [0.42631531, 0.81078236, 0.72255679, 0.39643148, 0.2277075 ],
        [0.47884527, 0.53980622, 0.23622995, 0.56372565, 0.29230751]],

       [[0.46593241, 0.81080941, 0.82545989, 0.58912935, 0.71400334],
        [0.219521  , 0.15256911, 0.32431803, 0.25685402, 0.24604937],
        [0.71186855, 0.02192046, 0.52164605, 0.80627708, 0.45724321],
        [0.41354711, 0.97433385, 0.61696812, 0.88580826, 0.51439986],
        [0.0553813 , 0.95466926, 0.71680461, 0.43870809, 0.075481  ]]])

## ndarray基础操作

In [65]:
A = np.ones(shape=(3, 5), dtype=int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [66]:
A.ndim

2

In [67]:
A.shape

(3, 5)

In [68]:
A.size

15

In [69]:
# reshape 修改数组维度
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x = a.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
a.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

a.reshape(-1, 2)

## 取值操作

In [78]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
X[0]

array([0, 1, 2, 3, 4])

In [83]:
X[-1]

array([10, 11, 12, 13, 14])

In [86]:
X[0][0] # 不推荐

0

In [88]:
X[(1,1)]

6

In [89]:
X[0,2]

2

## 切片  一维和二维

In [91]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a[0:5]

array([0, 1, 2, 3, 4])

In [93]:
a[:5]

array([0, 1, 2, 3, 4])

In [94]:
a[5:]

array([5, 6, 7, 8, 9])

In [95]:
a[0:8:2]

array([0, 2, 4, 6])

In [96]:
a[::2]

array([0, 2, 4, 6, 8])

In [97]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 二维数组的切片

In [98]:
X 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
# 取前2行前3列
X[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [101]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [102]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [103]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [104]:
## 行变列，列变行
X.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 矩阵的合并

In [106]:
X1 = np.array([[22, 168], 
              [18, 187]])

In [108]:
X2 = np.array([[0],
               [1]])

In [110]:
X = np.concatenate([X1, X2], axis = 1)

In [111]:
X

array([[ 22, 168,   0],
       [ 18, 187,   1]])

## 聚合操作

In [113]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
np.sum(X)

105

In [115]:
np.max(X)

14

In [116]:
np.mean(X)

7.0

In [117]:
np.min(X)

0